# Generated by Django 5.0 on 2023-12-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_autentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
